### ISSUE TITLE
[Back End] [Hardware] Be able to end game

### ISSUE THREAD

**Issue by tongyliu** [fpm5022/Ping-Pong#14]
Have the ability to exit a game early (by holding down both touch sensors maybe?)

**Comment by tongyliu** [comment]
See this commit: https://github.com/fpm5022/Ping-Pong/commit/0d8b61df5399cb29e49fe14393ea44e7d4e79d4e

Also added a setting in config.js: `recordUnfinishedGames`
Set to true if you want to have games that are ended early affect the DB (record, elo, etc).
Otherwise games that are ended early aren't saved.

**Comment by mr-feek** [comment]
dope
